### ISSUE TITLE
OpenDropController3_2 Compile Error

### ISSUE THREAD

**Issue by bhclowers** [GaudiLabs/OpenDrop#19]
Now that we are back in the lab we are trying to communicate with our OpenDrop v3.2 using the processing code.  We are using processing 4.0b1 and the OpenDropController3_2 from the github master.  When we try to compile we get the following error:

`frame cannot be resolved to a variable`

The associated tracebacks seems to point to line 138.  Looking at the code I don't see the variable defined either (but maybe I missed it).  Is it part of the javax.swing package and if so how to do we get that integrated?

Any help would be appreciated and I hope it is something simple.

Cheers.

**Comment by GaudiLabs** [comment]
frame is a special keyword as part of the showMessageDialog command. It does not need to be defined. This error message however suggests to me that something with your processing installation must be wrong. Try reinstalling the processing environment.

Best,
Urs

On 15 September 2021 20:48:59 CEST, bhclowers ***@***.***> wrote:
>Now that we are back in the lab we are trying to communicate with our OpenDrop v3.2 using the processing code.  We are using processing 4.0b1 and the OpenDropController3_2 from the github master.  When we try to compile we get the following error:
>
>`frame cannot be resolved to a variable`
>
>The associated tracebacks seems to point to line 138.  Looking at the code I don't see the variable defined either (but maybe I missed it).  Is it part of the javax.swing package and if so how to do we get that integrated?
>
>Any help would be appreciated and I hope it is something simple.
>
>Cheers.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenDrop/issues/19
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bhclowers** [comment]
I just wanted to provide a follow-up.  This issue appears to be associated with the beta version of Processing 4.0b1. After trying multiple computers, it took me way too long to try out 3.5.  The older version of Processing worked fine.  In the release notes they highlight that processing moved from Java 8 to Java 11. I would guess that is the issue. Hope this helps someone else.
