### ISSUE TITLE
Do you have Bill of Materials of OpenDrop V2?

### ISSUE THREAD

**Issue by dr-data** [GaudiLabs/OpenDrop#2]

**Comment by GaudiLabs** [comment]
For the V21 the BOM is in the corresponding folder of the repo.

On July 6, 2016 9:33:57 AM GMT+02:00, dr-data <notifications@github.com> wrote:
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenDrop/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
