### ISSUE TITLE
Is the online platform source code open source?

### ISSUE THREAD

**Issue by faruqsandi** [GaudiLabs/OpenDrop#22]
Hello there!

Is the online platform source code open source?
![image](https://github.com/GaudiLabs/OpenDrop/assets/965723/c4cb6ba5-b46f-4f96-b5ad-40a2be257d89)

Thanks.

**Comment by GaudiLabs** [comment]
Hi there
Sure, you find the code for the OpenDrop Online Platform here:
https://github.com/GaudiLabs/DigitalBiologyPlatform

What would  be your contribution?


On 22 February 2024 05:39:37 CET, Faruq Sandi ***@***.***> wrote:
>Hello there!
>
>Is the online platform source code open source?
>![image](https://github.com/GaudiLabs/OpenDrop/assets/965723/c4cb6ba5-b46f-4f96-b5ad-40a2be257d89)
>
>Thanks.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenDrop/issues/22
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
🧪 GaudiLabs LLC
Urs Gaudenz
Email: ***@***.***
www.gaudi.ch

**Comment by faruqsandi** [comment]
How the hell I missed it!
No, I will not contributing, my coworker is.

Thank you.
