### ISSUE TITLE
DIY NanoDrop linkes here

### ISSUE THREAD

**Issue by guysoft** [GaudiLabs/OpenDrop#3]
Hey,
The page http://wlu18www30.webland.ch/wiki/DIY_NanoDrop links here.
That project is to build a build DIY Microvolume Spectrophotometers.
Does this exist in the repo? If not do you know where that is?

**Comment by GaudiLabs** [comment]
Hi. The DIY Nanodrop moved here: http://www.gaudi.ch/GaudiLabs/?page_id=328 Will update the links. Urs

**Comment by guysoft** [comment]
Been a while, if there was a way for me to edit the wiki I could fix it

**Comment by GaudiLabs** [comment]
Link is fixed.

**Comment by josephshenekji** [comment]
@GaudiLabs 
greetings mr. urs
the link of public lab isn't working, is there a problem with it?
