### ISSUE TITLE
Droplets are not moving 

### ISSUE THREAD

**Issue by tomdertech** [GaudiLabs/OpenDrop#5]
Hi,

I have recreated stripped down opendrop (although at the moment I am using an external HV PSU). I do not have the screen and I have disabled the joystick. I have defined a start position `drop[0].begin(1,3)` and have set the code to loop between shifting right one position and then back left one position, however my droplet does not move.

**Testing & Setup**

Electrically I have proven that the voltage switches between the electrodes I expect. I have added a 3 second delay between each transition.

I have used Saran wrap pulled tight and held in position with double sided kapton tape. I have used a silicone oil on the electrodes and RainX (car windscreen repellant) as the hydrophobic coating on the droplet side of the saran wrap - you can see this here with the droplet.
![img_20170612_163716](https://user-images.githubusercontent.com/7968388/27042858-2014f864-4f90-11e7-9ff4-49b46facc956.jpg)

I have used ITO coated glass and used the copper tape method to connect to it. The conductive side is treated with RainX and faced down against the droplet with some tape to pack it. This can be seen here.
![img_20170612_163753](https://user-images.githubusercontent.com/7968388/27042916-5483d55c-4f90-11e7-8ded-b42062356096.jpg)

And when it is all together it looks like this
![img_20170612_164126](https://user-images.githubusercontent.com/7968388/27042937-6336a5ac-4f90-11e7-9f0d-98b0b05e73d5.jpg)

But the droplet does not move ... what should I try/am I missing?

Thanks.
Regards,
Tom

**Comment by GaudiLabs** [comment]
Follow the instructions here:
http://www.gaudi.ch/OpenDrop/?p=116
Urs
