### ISSUE TITLE
Tantalum Cap Not Rated

### ISSUE THREAD

**Issue by biomurph** [GaudiLabs/OpenDrop#9]
The cap you specify in your BOM for C1 is not rated at 35V

https://www.mouser.com/ProductDetail/AVX/TPSD107K016R0125?qs=sGAEpiMZZMuEN2agSAc2pqveSFvydLQ7ik6YjlyIzQo%3d

It's rated at 16V. Do you have the correct part number for the 35V rating?

btw, I have boards from your design on order from PCB pool. Should arrive early next week.

**Comment by GaudiLabs** [comment]
Ok, cool. The version 3 has still bugs/things to improve. As I said I am just now working on fixing this and will push then. Please correct bugs or update when you see necessity. 

Urs


On 24 May 2018 18:06:01 CEST, Joel Murphy <notifications@github.com> wrote:
>Hey Urs,
>
>Yeah, I'm working on the badge.
>Thought I would go for your latest design with the ARM, and also
>thought it would be nice to have more people working on it with you.
>Yes, PCB Pool is Germany, I think. They also have offices in Ireland
>somehow...
>
>I did get feedback from their cam operator. Check the PDF (needs to be
>opened in acrobat to change layer visibility.
>
>Purchasing BOM now... What's the speaker you're using? Seems the BOM
>you have is out of date, as it specifies a micro USB connector. I found
>the Amphenol part on digikey.
>[02913i_w.pdf](https://github.com/GaudiLabs/OpenDrop/files/2036189/02913i_w.pdf)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenDrop/issues/9#issuecomment-391770301

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by biomurph** [comment]
Will do. I think I will need to fork it again... had a github glitch on my end.

Cheers!
